name: Build 

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./Sovtech.ChuckSwapi.sln
    - name: Build
      run: dotnet build ./Sovtech.ChuckSwapi.sln --configuration Release 
    - name: Test
      run: dotnet test ./Sovtech.ChuckSwapi.sln --configuration Release --no-build --verbosity normal
