version: "3"
services: 
    proxy:
        build: 
            context: ./Proxy
            dockerfile: Dockerfile
        restart: always
    client:
        build:
            context: ./Client
            dockerfile: Dockerfile
    api:
        build: 
            context: ./API
            dockerfile: src/Sovtech.ChuckSwapi.Api/Dockerfile