version: '3.4'

services:
  sovtech.chuckswapi.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80 
    ports:
      - "8081:443"
      - "8080:80"
    volumes:
      - ${APPDATA}/tmp:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/tmp:/root/.aspnet/https:ro